# Generated by Django 4.1.7 on 2023-06-21 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lzycrazy', '0002_alter_productchat_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productchats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='lzycrazy.product')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productchat_receiver', to='lzycrazy.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productchat_sender', to='lzycrazy.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Productchat',
        ),
    ]
